name: AAA

on:
  workflow_dispatch:
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 下载
        run: |
          mkdir -p /opt/musl_gcc
          wget -q -c https://download1.dd-wrt.com/dd-wrtv2/downloads/toolchains/toolchains.tar.xz -P /opt/musl_gcc/
          tar xf /opt/musl_gcc/toolchains.tar.xz -C /opt/musl_gcc/
          cd /opt/musl_gcc
          rm -rf toolchain-x86_64_gcc-13.1.0_musl toolchain-powerpc_gcc-4.6-linaro_uClibc-0.9.33 toolchain-powerpc_e300c3_gcc-4.8-linaro_uClibc-0.9.33.2 
          rm -rf toolchain-powerpc_8540_gcc-12.2.0_musl toolchain-i386_pentium_gcc-8.2.0_musl toolchain-i386_pentium-mmx_gcc-10.2.0_musl
          rm -rf toolchains.tar.xz toolchain-powerpc_603e_gcc-12.2.0_musl toolchain-i386_pentium4_gcc-9.2.0_musl brcm24 sources staging_dir_powerpc
          tar -czf ddwrt-mips_mips32_gcc-8.2.0_musl.tar.gz toolchain-mips_mips32_gcc-8.2.0_musl
          tar -czf ddwrt-mips_24kc_gcc-13.1.0_musl.tar.gz toolchain-mips_24kc_gcc-13.1.0_musl
          tar -czf ddwrt-mips_24kc_gcc-12.2.0_musl.tar.gz toolchain-mips_24kc_gcc-12.2.0_musl
          tar -czf ddwrt-mipsel_mips32_gcc-13.1.0_musl.tar.gz toolchain-mipsel_mips32_gcc-13.1.0_musl
          tar -czf ddwrt-mipsel_gcc4.1.2.tar.gz toolchain-mipsel_gcc4.1.2
          tar -czf ddwrt-mipsel_gcc-linaro_uClibc-0.9.32.tar.gz toolchain-mipsel_gcc-linaro_uClibc-0.9.32
          tar -czf ddwrt-mipsel_1004kc+dsp_gcc-5.1.0_musl-1.1.10.tar.gz toolchain-mipsel_1004kc+dsp_gcc-5.1.0_musl-1.1.10
          tar -czf ddwrt-mipsel_74kc_gcc-13.1.0_musl.tar.gz toolchain-mipsel_74kc_gcc-13.1.0_musl
          tar -czf ddwrt-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2.tar.gz toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2
          tar -czf ddwrt-mipsel_24kc_gcc-13.1.0_musl.tar.gz toolchain-mipsel_24kc_gcc-13.1.0_musl
          tar -czf ddwrt-mips64_octeonplus_64_gcc-13.1.0_musl.tar.gz toolchain-mips64_octeonplus_64_gcc-13.1.0_musl
          tar -czf ddwrt-arm_mpcore+vfp_gcc-13.1.0_musl_eabi.tar.gz toolchain-arm_mpcore+vfp_gcc-13.1.0_musl_eabi
          tar -czf ddwrt-arm_cortex-a15+neon-vfpv4_gcc-13.1.0_musl_eabi.tar.gz toolchain-arm_cortex-a15+neon-vfpv4_gcc-13.1.0_musl_eabi
          tar -czf ddwrt-arm_cortex-a9_gcc-13.1.0_musl_eabi.tar.gz toolchain-arm_cortex-a9_gcc-13.1.0_musl_eabi
          tar -czf ddwrt-arm_cortex-a9+vfpv3-d16_gcc-13.1.0_musl_eabi.tar.gz toolchain-arm_cortex-a9+vfpv3-d16_gcc-13.1.0_musl_eabi
          tar -czf ddwrt-arm_cortex-a9+neon_gcc-13.1.0_musl_eabi.tar.gz toolchain-arm_cortex-a9+neon_gcc-13.1.0_musl_eabi
          tar -czf ddwrt-armeb_xscale_gcc-13.1.0_musl.tar.gz toolchain-armeb_xscale_gcc-13.1.0_musl
          tar -czf ddwrt-aarch64_generic_gcc-13.1.0_musl.tar.gz toolchain-aarch64_generic_gcc-13.1.0_musl
      - name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          body: |
           各平台的toolchain编译工具链
          tag_name: Armada370-ToolChain
          files: |
                 /opt/musl_gcc/ddwrt-mips_mips32_gcc-8.2.0_musl.tar.gz
                 /opt/musl_gcc/ddwrt-mips_24kc_gcc-13.1.0_musl.tar.gz
                 /opt/musl_gcc/ddwrt-mips_24kc_gcc-12.2.0_musl.tar.gz
                 /opt/musl_gcc/ddwrt-mipsel_mips32_gcc-13.1.0_musl.tar.gz
                 /opt/musl_gcc/ddwrt-mipsel_gcc4.1.2.tar.gz
                 /opt/musl_gcc/ddwrt-mipsel_gcc-linaro_uClibc-0.9.32.tar.gz
                 /opt/musl_gcc/ddwrt-mipsel_1004kc+dsp_gcc-5.1.0_musl-1.1.10.tar.gz
                 /opt/musl_gcc/ddwrt-mipsel_74kc_gcc-13.1.0_musl.tar.gz
                 /opt/musl_gcc/ddwrt-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2.tar.gz
                 /opt/musl_gcc/ddwrt-mipsel_24kc_gcc-13.1.0_musl.tar.gz
                 /opt/musl_gcc/ddwrt-mips64_octeonplus_64_gcc-13.1.0_musl.tar.gz
                 /opt/musl_gcc/ddwrt-arm_mpcore+vfp_gcc-13.1.0_musl_eabi.tar.gz
                 /opt/musl_gcc/ddwrt-arm_cortex-a15+neon-vfpv4_gcc-13.1.0_musl_eabi.tar.gz
                 /opt/musl_gcc/ddwrt-arm_cortex-a9_gcc-13.1.0_musl_eabi.tar.gz
                 /opt/musl_gcc/ddwrt-arm_cortex-a9+vfpv3-d16_gcc-13.1.0_musl_eabi.tar.gz
                 /opt/musl_gcc/ddwrt-arm_cortex-a9+neon_gcc-13.1.0_musl_eabi.tar.gz
                 /opt/musl_gcc/ddwrt-armeb_xscale_gcc-13.1.0_musl.tar.gz
                 /opt/musl_gcc/ddwrt-aarch64_generic_gcc-13.1.0_musl.tar.gz
      
