name: AAA

on:
  workflow_dispatch:
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: 下载
        run: |
          mkdir -p /opt/musl_gcc
          wget -q -c https://download1.dd-wrt.com/dd-wrtv2/downloads/toolchains/toolchains.tar.xz -P /opt/musl_gcc/
          tar xf /opt/musl_gcc/toolchains.tar.xz -C /opt/musl_gcc/
          cd /opt/musl_gcc 
          rm -rf toolchain-x86_64_gcc-13.1.0_musl toolchain-powerpc_gcc-4.6-linaro_uClibc-0.9.33 toolchain-powerpc_e300c3_gcc-4.8-linaro_uClibc-0.9.33.2 
          rm -rf toolchain-powerpc_8540_gcc-12.2.0_musl toolchain-i386_pentium_gcc-8.2.0_musl toolchain-i386_pentium-mmx_gcc-10.2.0_musl
          rm -rf toolchains.tar.xz toolchain-powerpc_603e_gcc-12.2.0_musl toolchain-i386_pentium4_gcc-9.2.0_musl brcm24 sources staging_dir_powerpc
          cd /opt
          tar -czf ddwrt-musl.tar.gz musl_gcc
      - name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          tag_name: Armada370-ToolChain
          files: /opt/ddwrt-musl.tar.gz
      
