name: 编译群晖ds213j_vnt-cli

on:
  #schedule:
    #- cron: '0 3 * * *'
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: 检查代码仓库
        uses: actions/checkout@v3
      - 
        name: 编译
        run: |
          mkdir -p /opt/musl_gcc 
          wget -c https://github.com/lmq8267/vnt-cli/releases/download/Armada370-ToolChain/armada370-gcc493_glibc220_hard-GPL.txz -P /opt/musl_gcc/
          tar -Jxvf /opt/musl_gcc/armada370-gcc493_glibc220_hard-GPL.txz -C /opt/musl_gcc/
          rustup target add armv7-unknown-linux-gnueabihf
          export PATH=$PATH:/opt/musl_gcc/arm-unknown-linux-gnueabi/bin
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/musl_gcc/arm-unknown-linux-gnueabi/lib
          rustup target add armv7-unknown-linux-gnueabihf
          cat >>~/.cargo/config <<EOF
          [target.armv7-unknown-linux-gnueabihf]
          linker = "arm-unknown-linux-gnueabi-gcc"
          #rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]  #编译静态选项 默认编译动态版
          EOF
          git clone https://github.com/lbl8603/vnt /opt/vnt
          cd /opt/vnt
          #默认编译全功能版 --features openssl-vendored
          cargo build --package vnt-cli --target=armv7-unknown-linux-gnueabihf --release --features openssl-vendored
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "build_tag=$(grep "version" /opt/vnt/common/Cargo.toml | cut -d '"' -f 2)" >> $GITHUB_ENV

      - name : 上传
        uses: actions/upload-artifact@master
        with:
         name: vnt-cli
         path: /opt/vnt/target/armv7-unknown-linux-gnueabihf/release/vnt-cli
      #- 
      #  name: 发布
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    token: ${{ secrets.c8 }}
      #    body: |
      #    > ### 编译时间 ：${{ env.build_time }}
           
      #     **适用于群晖ds213j**
           
      #    **[官方更新说明](https://github.com/lbl8603/vnt/releases)**
      #    tag_name: ${{ env.build_time }}
      #    files: |
      #        /opt/vnt/target/armv7-unknown-linux-gnueabihf/release/vnt-cli
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
